import { StyleSheet, Platform } from 'react-native';

export const s = StyleSheet.create({
  master: { flex: 1, backgroundColor: '#0A0A0A' },
  h: { height: 100, paddingHorizontal: 20, paddingTop: 45, backgroundColor: '#111', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  b: { color: '#FFF', fontSize: 19, fontWeight: '900' },
  secureLink: { fontSize: 9, color: '#B0B0B0' },
  dot: { width: 10, height: 10, borderRadius: 5 },
  bb: { backgroundColor: '#111', padding: 15, borderRadius: 15, marginBottom: 20 },
  bg: { height: 6, backgroundColor: '#222', borderRadius: 3, marginVertical: 10 },
  bf: { height: 6, backgroundColor: '#D4AF37', borderRadius: 3 },
  card: { height: 160, borderRadius: 20, overflow: 'hidden', marginBottom: 15, backgroundColor: '#111' },
  img: { flex: 1, width: undefined, height: undefined, opacity: 0.6 },
  overlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 15, backgroundColor: 'rgba(0,0,0,0.6)' },
  city: { color: '#FFF', fontSize: 21, fontWeight: 'bold' },
  cl: { fontSize: 17, fontWeight: 'bold' },
  radarOuter: { alignItems: 'center', marginTop: 30 },
  rcir: { width: 320, height: 320, borderRadius: 160, borderWidth: 2, borderColor: '#4CD964', overflow: 'hidden' },
  mapaFondo: { ...StyleSheet.absoluteFillObject, opacity: 0.5 },
  mapGrid: { ...StyleSheet.absoluteFillObject, justifyContent: 'center', alignItems: 'center' },
  anillo: { position: 'absolute', borderWidth: 1, borderColor: 'rgba(76,217,100,0.3)', borderRadius: 200 },
  ejeV: { position: 'absolute', width: 1, top: 0, bottom: 0, backgroundColor: 'rgba(76,217,100,0.3)' },
  ejeH: { position: 'absolute', left: 0, right: 0, height: 1, backgroundColor: 'rgba(76,217,100,0.3)' },
  radarEje: { width: 320, height: 320, position: 'absolute' },
  sw: { width: 160, height: 160, backgroundColor: 'rgba(76,217,100,0.2)', borderTopLeftRadius: 160 },
  punto: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  radarPing: { position: 'absolute', width: 20, height: 20, borderRadius: 10, opacity: 0.4 },
  radarDot: { width: 6, height: 6, borderRadius: 3 },
  radarLabel: { color: '#4CD964', fontSize: 8, fontWeight: 'bold', marginTop: 4, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  radarText: { color: '#4CD964', fontSize: 11, marginTop: 15, fontFamily: 'monospace' },
  vc: { backgroundColor: '#1A1A1A', padding: 15, borderRadius: 15, flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  vi: { width: 40, height: 60, borderRadius: 5 },
  vt: { color: '#FFF', fontWeight: 'bold' },
  vs: { color: '#B0B0B0', fontSize: 11 },
  vl: { color: '#FFF', marginBottom: 10, fontWeight: 'bold' },
  sosContainer: { position: 'absolute', top: 20, left: 28, zIndex: 100 },
  sos: { 
    width: 52, height: 52, borderRadius: 26, backgroundColor: '#FF3B30', 
    justifyContent: 'center', alignItems: 'center', 
    shadowColor: '#FF3B30', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.9, shadowRadius: 15, elevation: 15,
    borderWidth: 1.5, borderColor: 'rgba(255, 59, 48, 0.5)'
  },
  sosBtn: { position: 'absolute', bottom: 125, left: 20, width: 65, height: 65, borderRadius: 33, backgroundColor: '#000', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#FF3B30', elevation: 10, shadowColor: '#FF3B30', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.5, shadowRadius: 8 },
  chatBubble: { position: 'absolute', bottom: 125, right: 20, width: 65, height: 65, borderRadius: 33, backgroundColor: '#AF52DE', justifyContent: 'center', alignItems: 'center', elevation: 10, shadowColor: '#AF52DE', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.5, shadowRadius: 8 },
  sosChat: { position: 'absolute', top: 20, right: 15, width: 52, height: 52, borderRadius: 26, backgroundColor: '#222', borderWidth: 1, borderColor: '#AF52DE', justifyContent: 'center', alignItems: 'center', zIndex: 100 },
  topPanel: { position: 'absolute', top: 38, left: 0, right: 0, alignItems: 'center', zIndex: 90 },
 village: { flexDirection: 'row', alignItems: 'center' }, // Placeholder for context if needed
  nav: { height: 90, flexDirection: 'row', backgroundColor: '#111', borderTopWidth: 1, borderColor: '#222', paddingBottom: 25 },
  ni: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  mf: { flex: 1, backgroundColor: 'rgba(0,0,0,0.9)', justifyContent: 'center', alignItems: 'center' },
  mc: { width: '85%', backgroundColor: '#1A1A1A', padding: 20, borderRadius: 25, alignItems: 'center', maxHeight: '80%' },
  mt: { color: '#FFF', fontSize: 19, fontWeight: 'bold' },
  bt: { width: '100%', padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  btx: { color: '#FFF', fontWeight: 'bold' },
  laser: { position: 'absolute', left: 0, right: 0, height: 4, backgroundColor: '#AF52DE', zIndex: 100 },
  logBox: { backgroundColor: '#111', padding: 15, borderRadius: 15 },
  logItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, borderBottomWidth: 1, borderBottomColor: '#222', paddingBottom: 10 },
  legendBox: { backgroundColor: '#111', padding: 20, borderRadius: 20, marginTop: 30, width: 320, borderWidth: 1, borderColor: '#222' },
  filterRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
  switchOn: { width: 40, height: 20, borderRadius: 10, backgroundColor: '#4CD964', justifyContent: 'center', alignItems: 'flex-end', padding: 2 },
  switchOff: { width: 40, height: 20, borderRadius: 10, backgroundColor: '#333', justifyContent: 'center', alignItems: 'flex-start', padding: 2 },
  dotOn: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#FFF' },
  dotOff: { width: 16, height: 16, borderRadius: 8, backgroundColor: '#666' },
  statsCard: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: '#111', padding: 20, borderRadius: 20 },
  statBox: { alignItems: 'center' },
  chatHead: { flexDirection: 'row', justifyContent: 'space-between', padding: 20, borderBottomWidth: 1, borderBottomColor: '#222', backgroundColor: '#0A0A0A' },
  chatInputWrap: { flexDirection: 'row', padding: 15, backgroundColor: '#111', borderTopWidth: 1, borderTopColor: '#222' },
  chatInput: { flex: 1, backgroundColor: '#0A0A0A', borderRadius: 20, paddingHorizontal: 15, color: '#FFF', height: 45 },
  chatBtn: { width: 45, height: 45, backgroundColor: '#AF52DE', borderRadius: 22.5, justifyContent: 'center', alignItems: 'center', marginLeft: 10 },
  compBanner: { backgroundColor: '#FFD700', paddingVertical: 14, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 3, borderBottomColor: '#B8860B', position: 'relative', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 4, elevation: 8 },
  compText: { color: '#000', fontWeight: '900', fontSize: 13, letterSpacing: 0.5, textAlign: 'center' },
  compSub: { color: '#444', fontSize: 10, fontWeight: 'bold', marginTop: 3, opacity: 0.8, textAlign: 'center' },
  compClose: { position: 'absolute', right: 12, top: '50%', marginTop: -15, width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(0,0,0,0.08)', justifyContent: 'center', alignItems: 'center' },
  voiceBtn: { paddingHorizontal: 15, paddingVertical: 8, borderRadius: 10, borderWidth: 1, borderColor: '#AF52DE', marginRight: 10 },
  voiceBtnSelected: { backgroundColor: '#AF52DE' }
});
